### ISSUE TITLE
add /iwbep/if_mgw_appl_srv_runtime to /iwbep/cl_mgw_push_abs_data

### ISSUE THREAD

**Issue by gregorwolf** [abaplint/deps#104]

**Comment by larshp** [comment]
if its small fast changes, feel free to just open the PR 😄 no need for an issue, only if there is design stuff or to avoid multiple people working on the same thing

**Comment by gregorwolf** [comment]
So used to it in my current project. I use it for the branch name :-).

**Comment by larshp** [comment]
also feel free to open the issues 😄
