### ISSUE TITLE
Gateway service extension classes syntax_check fails over class definitions

### ISSUE THREAD

**Issue by geert-janklaps** [abaplint/deps#13]
When running abaplint for gateway extension classes (*DPC_EXT and *MPC_EXT) the syntax_check fails over global class definitions (inherited) not being available in the project.

![image](https://user-images.githubusercontent.com/2744548/71688738-bb61fd80-2da0-11ea-94ea-d470b2839848.png)

Example available in repository:
https://gitlab.com/geertjanklaps/abap-openapi-ui/tree/development

Pipeline log:
https://gitlab.com/geertjanklaps/abap-openapi-ui/-/jobs/392748459

**Comment by larshp** [comment]
try again, added in https://github.com/abaplint/deps/commit/8537bf3c1cfd252822eec0a09e389bd576be78c9

**Comment by geert-janklaps** [comment]
Works fine now!
Thanks!
