### ISSUE TITLE
Super class "cl_abap_behavior_handler" not found or contains errors (check_syntax)

### ISSUE THREAD

**Issue by Mcreve** [abaplint/deps#167]
When trying to have abaplint validate code for RAP behavior implementation the classes 'cl_abap_behavior_handler' and 'cl_abap_behavior_saver' cannot pass the syntax test. 
These are standard classes used for RAP implementations.
(I also have a question regarding expanding the "object_naming" rule with CDS views, but I'm unsure where to put this issue)

Kind regards,
Maxim

**Comment by larshp** [comment]
feel free to open a pull request with the classes, only add the stuff that you need

object_naming: questions regarding rules should go to https://github.com/abaplint/abaplint

**Comment by Mcreve** [comment]
@larshp I will try to pick this up, thank you

**Comment by larshp** [comment]
I'm starting this now
